## PCA exercise with the virus3 data

### INFO
- Use the data from the "VIRUS3.DAT" data to do a PCA analysis.
- The colums of the data set are describing several features of virusses.
- We want to find out how many different types of virusses we have.
- The rows are the measurements of a virus.
### Tasks 
- The main question is can we recognize groupings?
- How many different groups can we identfy, are these different kind of virusses?
- How many principal components do you need to preserve 95% of the variance?
- Identfy the optimal number of groups according to you analysis.
- Don't forget to document your code!
- Try to do all tasks and answer all questions!

### Questions
1. How many features does the data set have?
2. Are you using a pandas data frame or a numpy array for your pca analysis?
3. How many different groups does the data set have according to the data frame?
4. How many principal components are the optimum for this data set?
5. Plot your principal components together in several plots, e.g. PC2 oder PC1, PC3 over PC2, ...

In [1]:
from sklearn import datasets
# Scikit-Learn â‰¥0.20 is required
import sklearn as sk
assert sk.__version__ >= "0.20"
from sklearn.cluster import KMeans

import matplotlib.pylab as plt
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline

#### We are just naming the different features, so it is a bit more comfortable to work with.

In [2]:
data = pd.read_csv('VIRUS3.DAT', delimiter= '\s+', index_col=False)
data.columns=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j",
                         "k", "l", "m", "n", "o", "q", "r", "s"]

data.head(5)

    a   b   c   d  e  f   g  h   i  j  k   l  m  n  o  q   r  s
0  12  11   9  12  6  5  12  1   9  1  7  12  5  6  0  4   8  2
1  18  16  16  16  8  6  14  1  14  0  9  12  4  8  0  2  11  3
2  18  16  15  19  8  6  11  1  15  1  7  13  5  8  0  2   9  3
3  17  13  13  22  8  4  18  1  10  3  8  11  7  6  1  2  10  2
4  16  13  16  21  9  3  17  1  10  4  7  12  7  5  1  2  11  3